"""make profile_picture nullable

Revision ID: 4272edc0a264
Revises: 
Create Date: 2025-06-14 17:36:04.517353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4272edc0a264'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('students', sa.Column('fees', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_students_name'), table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.drop_column('students', 'fees')
    op.drop_column('students', 'profile_picture')
    # ### end Alembic commands ###
